name: Frontend CD

on:
  workflow_run:
    workflows: ["Frontend CI"]
    types:
      - completed

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t my-frontend-app:${{ github.sha }} .
          docker tag my-frontend-app:${{ github.sha }} mydockerhubuser/my-frontend-app:latest
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push mydockerhubuser/my-frontend-app:latest

      - name: Deploy with Terraform
        run: |
          cd infra
          terraform init
          terraform apply -auto-approve
